on:
  push:
    branches:
      - master
name: üöÄ Deploy website on push to master
jobs:
  web-deploy:
    name: üöÄ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ‚è≥ Preparing files
        uses: actions/checkout@v2.3.2

      - name: ‚è≥ Preparing Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: üî® Building project
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          CI: false

      - name: üîÅ Upload files via FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_URL }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "build"
          dist_target_dir: "/"
          # WARNING: OPTION BELOW DELETES/REPLACES ALL REMOTE FILES THAT'S NOT IN BUILD! DONT USE TRUE FOR MAIN WEB DEPLOY!
          delete: "false"
